#!/bin/bash
# vim: set ft=sh:
# This script helps doing with coog api image

get_dir() {
        local script_path; script_path=$(readlink -f "$0")
        local script_dir; script_dir=$(dirname "$script_path")
        echo "$script_dir"
}

_args() {
        local args
        args="$args --link $REDIS_CONTAINER:redis -e COOG_API_REDIS_URL=//redis:6379 -e COOG_API_REDIS_DB=$API_REDIS_DB"
        args="$args --link $NGINX_CONTAINER:coog -e COOG_API_COOG_URL=http://coog:80 -e COOG_API_COOG_DB=$COOG_DB_NAME"
        args="$args -p 80$NGINX_PUB_PORT:3000"
        [ ! -z "$DEBUG" ] && args="$args -e DEBUG=$DEBUG"
        echo "$args"

}

_run() {
        docker run \
                $DOCKER_DAEMON_OPTS \
                --name "$API_CONTAINER" \
                $(_args) "$API_IMAGE" "$@"
}

_docker() {
        docker "$@" "$API_CONTAINER"
}

usage() {
        echo
        echo Available commands
        echo
        echo "  run       -> runs an api docker image"
        echo "  <action>  -> calls docker action on api container"
        echo
}

main() {
        source "$(get_dir)/config"
        #
        [ -z "$1" ] && usage && return 0
        local cmd; cmd="$1"; shift
        #
        [ "$cmd" = "run" ] && { _run "$@"; return $?; }
        _docker "$cmd" "$@"
}

main "$@"
