#!/bin/bash

usage() {
    echo
    echo "Usage:"
    echo
    echo "  ./backup <container_name> <db_name>"
    echo
    echo
    echo
}

[[ $# -ne 2 ]] && usage && exit 1
[[ -z "$COOG_DATA" ]] && echo "\$COOG_DATA must be set" && exit 1

container_name="$1"
db_name="$2"

dump_database() {
    backup_path="$1"
    docker exec $container_name pg_dump -Fc -d $db_name -U postgres > $backup_path
}

dump_attachments() {
    backup_path="$1"
    cd $COOG_DATA/coog/
    tar -cz -f "$backup_path" edm/
    cd -
}

check_backup() {
    if [[ $? -eq 0 ]]; then
        echo "backup $1 --> ok"
    else
        echo "backup $1 --> ko"
    fi
}

if [[ $(date '+%m%d') == 0101 ]]; then
    dump_database "/mnt/support-backup/db-$(date '+%Y').dump.gz"
fi

if [[ $(date '+%d') == 01 ]]; then
    dump_database "/mnt/support-backup/db-$(date '+%B').dump.gz"
fi

if [[ $(date '+%u') == 0 ]]; then
    dump_database "/mnt/support-backup/db-week-$(date '+%V').dump.gz"
fi

dump_database "/mnt/coog_backup/db-$db_name-$(date '+%A').dump.gz"
check_backup "db"
dump_attachments "/mnt/coog_backup/attachments-$db_name-$(date '+%A').tar.gz"
check_backup "attachments"
