#!/bin/bash
# This command builds a Coog Docker image
#
# The script uses `coog docker` command which requires
#     - the list of coog repos to consider
#     - for each repo the git tag / branch to archive
#     - the first repo tag is used as the image tag
#
# For example: `coog docker coog:1.6 trytond-modules:1.6 trytond:1.6` builds
#              an image tagged: coog/coog:1.6
#
# This script will read its informations from `tags` file

repos=`cat ./tags | xargs echo`

# when behind a proxy
# coog docker build "$repos" -- --build-arg http_proxy=http://myproxy.domain.com:8080
coog docker build "$repos"
