#!/bin/sh
# this script is used to run celery workers for migration

WORKERS=4

if [ ! -z "$1" ]; then
    WORKERS="$1"
fi

./coog celery "$WORKERS" roederer.file.import \
    migrator.party \
    migrator.company \
    migrator.group \
    migrator.address \
    migrator.bank \
    migrator.contact \
    migrator.contract \
    migrator.adhesions
