#!/bin/bash

# This command cleans images and volumes
#
# Based on https://www.calazan.com/docker-cleanup-commands/

docker ps -a | grep Exited | cut -d ' ' -f 1 | xargs docker rm
docker rmi `docker images -q -f dangling=true`
docker run -v /var/run/docker.sock:/var/run/docker.sock \
        -v /var/lib/docker:/var/lib/docker \
        --rm \
        martin/docker-cleanup-volumes
