#!/bin/bash
# This file is used to configure coog for docker
#-------------------------------------------------------------------------------#
# COOG CORE CONFIGURATIONS                                                      #
#-------------------------------------------------------------------------------#

COOG_IMAGE=`head -1 ./tags`	# name of the Image to use - extracts the first argument from `tags`
COOG_CONTAINER=coog		# The name of the container
COOG_DATA=/var/local/coog	# An absolute path to a docker volume
COOG_POSTGRES=postgres		# Name of docker container running postgres
COOG_REDIS=			# same but for redis
COOG_SENTRY=			# same but for `sentry`
COOG_WORKERS=4			# the number of daemons to run - WARNING: if you change this number don't forget to update nginx.conf 

#-------------------------------------------------------------------------------#
# COOG DATABASE CONFIGURATIONS                                                  #
#-------------------------------------------------------------------------------#

COOG_DB_SYS=postgresql		# the database system to use - default: `postgresql`
COOG_DB_HOST=			# REQUIRED - default: linked postgres container (POSTGRES)
COOG_DB_PORT=			# REQUIRED - default: linked postgres container (POSTGRES)
COOG_DB_USER=postgres		# REQUIRED - the database user name
COOG_DB_PASSWORD=postgres	# REQUIRED - the database user password
COOG_DB_NAME=coog		# name of the database ?? defaults too
COOG_DB_LANG=fr_FR		# database Locale - eg. fr_FR

#-------------------------------------------------------------------------------#
# COOG CACHE CONFIGURATIONS                                                     #
#-------------------------------------------------------------------------------#

COOG_CACHE_MODEL=		# Number of models stored in cache    - default: (tryton default)
COOG_CACHE_RECORD=		# Number of instances stored in cache - default: (tryton default)
COOG_CACHE_FIELD=		# Number of fields stored in cache    - default: (tryton default)
COOG_CACHE_COOG=		# default: (tryton default)
COOG_CAHCE_SYS=redis		# Cache application to use
COOG_CACHE_HOST=		# Cache hostname - default: linked redis container
COOG_CACHE_PORT=		# Cache port	 - default: linked redis container
COOG_CACHE_DB=			# The database number  - depends: COOG_CACHE_SYS

#-------------------------------------------------------------------------------#
# COOG ASYNC CONFIGURATIONS                                                     #
#-------------------------------------------------------------------------------#

COOG_ASYNC_SYS=			# application to use for asynchronous jobs - eg. celery
COOG_ASYNC_HOST=		# from linked celery
COOG_ASYNC_PORT=		# from linked celery
COOG_ASYNC_DB=			# database id to use

#-------------------------------------------------------------------------------#
# COOG SENTRY CONFIGURATIONS                                                     #
#-------------------------------------------------------------------------------#

COOG_SENTRY_PROTOCOL=          # Protocol to use - default: http
COOG_SENTRY_HOST=              # default: `./ip $COOG_SENTRY`
COOG_SENTRY_PORT=9000	       # 
COOG_SENTRY_PUB=pub            # should be retrieved from sentry app
COOG_SENTRY_SEC=sec            # should be retrieved from sentry app
COOG_SENTRY_PROJECT=project    # should be retrieved from sentry app

#-------------------------------------------------------------------------------#
# POSTGRES CORE CONFIGURATIONS                                                  #
#-------------------------------------------------------------------------------#

POSTGRES_IMAGE=postgres:9.4
POSTGRES_CONTAINER=postgres
POSTGRES_USERNAME=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DATA=/var/local/coog/

#-------------------------------------------------------------------------------#
# REDIS CORE CONFIGURATIONS                                                     #
#-------------------------------------------------------------------------------#

REDIS_IMAGE=redis:3.0
REDIS_CONTAINER=redis

#-------------------------------------------------------------------------------#
# SENTRY CORE CONFIGURATIONS                                                    #
#-------------------------------------------------------------------------------#

SENTRY_IMAGE=sentry:8
SENTRY_CONTAINER=sentry
SENTRY_POSTGRES=postgres              # name of running container to link
SENTRY_REDIS=redis                    # name of running container to link

SENTRY_DB_USER=postgres		      # database username
SENTRY_DB_PASSWORD=postgres	      # database password
SENTRY_DB_NAME=sentry		      # name of the database to use
SENTRY_REDIS_DB=9		      # the redis database index to use

# EOF
