#!/bin/bash
# vim: set ft=sh:
# This script helps doing with Coog image.
# More informations: https://docs.docker.com/engine/reference/run/

get_dir() {
        local script_path; script_path=$(readlink -f "$0")
        local script_dir; script_dir=$(dirname "$script_path")
        echo "$script_dir"
}

########
# args #
########

session_args() {
        [ ! -z "$COOG_SESSION_SUPERPWD" ] && echo "-e COOG_SESSION_SUPERPWD=$COOG_SESSION_SUPERPWD"
}

postgres_args() {
        local args
        if [ ! -z "$COOG_POSTGRES_HOST" ]
        then
                args="-e COOG_POSTGRES_HOST=$COOG_POSTGRES_HOST"
                [ ! -z "$COOG_POSTGRES_PORT" ] && args="$args -e COOG_POSTGRES_PORT=$COOG_POSTGRES_PORT"
        elif [ ! -z "$POSTGRES_CONTAINER" ]
        then
                args="--link $POSTGRES_CONTAINER:postgres"
                args="$args -e COOG_POSTGRES_HOST=postgres"
        else
                return 0
        fi
        echo "$args"
}

redis_args() {
        local args
        if [ ! -z "$COOG_REDIS_HOST" ]
        then
                args="-e COOG_REDIS_HOST=$COOG_REDIS_HOST"
                [ ! -z "$COOG_REDIS_PORT" ] && args="$args -e COOG_REDIS_PORT=$COOG_REDIS_PORT"
        elif [ ! -z "$REDIS_CONTAINER" ]
        then
                args="--link $REDIS_CONTAINER:redis"
                args="$args -e COOG_REDIS_HOST=redis"
        else
                return 0
        fi
        echo "$args"
}

db_args() {
        local args
        [ ! -z "$COOG_DB_LANG" ] && args="$args -e COOG_DB_LANG=$COOG_DB_LANG"
        [ ! -z "$COOG_DB_USER" ] && args="$args -e COOG_DB_USER=$COOG_DB_USER"
        [ ! -z "$COOG_DB_PASSWORD" ] && args="$args -e COOG_DB_PASSWORD=$COOG_DB_PASSWORD"
        [ ! -z "$COOG_DB_NAME" ] && args="$args -e COOG_DB_NAME=$COOG_DB_NAME"
        echo "$args"
}

cache_args() {
        local args
        [ ! -z "$COOG_CACHE_MODEL" ] && args="$args -e COOG_CACHE_MODEL=$COOG_CACHE_MODEL"
        [ ! -z "$COOG_CACHE_RECORD" ] && args="$args -e COOG_CACHE_RECORD=$COOG_CACHE_RECORD"
        [ ! -z "$COOG_CACHE_FIELD" ] && args="$args -e COOG_CACHE_FIELD=$COOG_CACHE_FIELD"
        [ ! -z "$COOG_CACHE_COOG" ] && args="$args -e COOG_CACHE_COOG=$COOG_CACHE_COOG"
        [ ! -z "$COOG_CACHE_DB" ] && args="$args -e COOG_CACHE_DB=$COOG_CACHE_DB"
        echo "$args"
}

celery_args() {
        [ ! -z "$COOG_CELERY_DB" ] && echo "-e COOG_CELERY_DB=$COOG_CELERY_DB"
}

rq_args() {
        [ ! -z "$COOG_RQ_DB" ] && echo "-e COOG_RQ_DB=$COOG_RQ_DB"
}

sentry_args() {
        local args
        if [ -z "$COOG_SENTRY_PROTOCOL" ] || [ -z "$COOG_SENTRY_HOST" ] || [ -z "$COOG_SENTRY_PORT" ]
        then
                if [ ! -z "$SENTRY_CONTAINER" ]
                then
                        args="--link $SENTRY_CONTAINER:sentry"
                        COOG_SENTRY_PROTOCOL=http
                        COOG_SENTRY_HOST=sentry
                        COOG_SENTRY_PORT=9000
                else
                        return
                fi
        fi
        if [ ! -z "$COOG_SENTRY_PUB" ] && [ ! -z "$COOG_SENTRY_SEC" ] && [ ! -z "$COOG_SENTRY_PROJECT" ]
        then
                args="$args -e COOG_SENTRY=$COOG_SENTRY_PROTOCOL://$COOG_SENTRY_PUB:$COOG_SENTRY_SEC@$COOG_SENTRY_HOST:$COOG_SENTRY_PORT/$COOG_SENTRY_PROJECT"
                echo "$args"
        fi
}

args() {
        local args
        args="-v /tmp:/tmp -v $COOG_VOLUME:/coog/io"
        if [ ! -z "$COOG_LOG_LEVEL" ]
        then
                args="$args -e LOG_LEVEL=$COOG_LOG_LEVEL"
        fi
        echo "$args $(session_args) $(postgres_args) $(redis_args) $(db_args) $(cache_args) $(celery_args) $(rq_args) $(sentry_args)"
}

###############
# entrypoints #
###############

init() {
        mkdir -p "$COOG_VOLUME"
        mkdir -p "$COOG_VOLUME"/conf
        mkdir -p "$COOG_VOLUME"/edm
        mkdir -p "$COOG_VOLUME"/batch
        [ ! -e "$COOG_VOLUME/conf/coog.conf" ] && touch "$COOG_VOLUME/conf/coog.conf"
        [ ! -e "$COOG_VOLUME/conf/batch.conf" ] && touch "$COOG_VOLUME/conf/batch.conf"
}

edit_app() {
        "$EDITOR" "$COOG_VOLUME/conf/coog.conf"
}

edit_batch() {
        "$EDITOR" "$COOG_VOLUME/conf/batch.conf"
}

version() {
        docker run -t --rm $(args) "$COOG_IMAGE" version
}

env() {
        docker run -t --rm $(args) "$COOG_IMAGE" env
}

conf() {
        docker run -t --rm $(args) "$COOG_IMAGE" conf
}

admin() {
        docker run -t --rm $(args) "$COOG_IMAGE" admin -v -d "$COOG_DB_NAME" "$@"
}

cron() {
        docker run -d $(args) --name "$COOG_CONTAINER-cron" "$COOG_IMAGE" cron "$@"
}

server() {
        [ -z "$1" ] && echo missing args && return 1
        docker run -d $(args) --name "$COOG_CONTAINER" "$COOG_IMAGE" wsgi "$@"
}

batch() {
        [ -z "$1" ] && echo missing args && return 1
        docker run -t --rm $(args) "$COOG_IMAGE" batch "$@"
}

celery() {
        [ -z "$1" ] && echo missing args && return 1
        docker run -d $(args) --name "$COOG_CONTAINER-celery" "$COOG_IMAGE" celery "$@"
}

rq() {
        [ -z "$1" ] && echo missing args && return 1
        local id; id=$1; shift
        docker run -d $(args) --name "$COOG_CONTAINER-rq-$id" "$COOG_IMAGE" rq "$@"
}

action() {
        docker "$@" "$COOG_CONTAINER"
}

########
# main #
########

usage() {
        echo
        echo Available commands
        echo
        echo "  init          -> init volume folder"
        echo "  edit-app      -> edits coog app config file"
        echo "  edit-batch    -> edits coog batch config file"
        echo "  version       -> gets image version (git trees)"
        echo "  env           -> gets container env vars"
        echo "  conf          -> gets container coog configuration"
        echo "  admin         -> launch admin utils - <args>"
        echo "  cron          -> starts coog cron"
        echo "  server        -> starts coog server - <workers nb>"
        echo "  batch         -> starts coog batch - <name> [args]"
        echo "  celery        -> starts celery workers - <workers nb> <queues>"
        echo "  rq            -> starts rq worker - <queues>"
        echo "  <action>      -> calls docker action on server container"
        echo
}

main() {
        source "$(get_dir)/config"
        #
        [ -z "$1" ] && usage && return 0
        local cmd; cmd="$1"; shift
        #
        [ "$cmd" = "init" ] && { init; return $?; }
        [ "$cmd" = "edit-app" ] && { edit_app; return $?; }
        [ "$cmd" = "edit-batch" ] && { edit_batch; return $?; }
        [ "$cmd" = "version" ] && { version; return $?; }
        [ "$cmd" = "env" ] && { env; return $?; }
        [ "$cmd" = "conf" ] && { conf; return $?; }
        [ "$cmd" = "admin" ] && { admin "$@"; return $?; }
        [ "$cmd" = "cron" ] && { cron "$@"; return $?; }
        [ "$cmd" = "server" ] && { server "$@"; return $?; }
        [ "$cmd" = "batch" ] && { batch "$@"; return $?; }
        [ "$cmd" = "celery" ] && { celery "$@"; return $?; }
        [ "$cmd" = "rq" ] && { rq "$@"; return $?; }
        action "$cmd" "$@"
}

main "$@"
