#!/bin/bash
# vim: set ft=sh:
# This script launches custom config script edition

get_dir() {
        local script_path; script_path=$(readlink -f "$0")
        local script_dir; script_dir=$(dirname "$script_path")
        echo "$script_dir"
}

main() {
        source "$(get_dir)/config"
        "$EDITOR" "$PREFIX/config"
}

main
