#!/bin/bash

if [ -z "$COOG_CODE_DIR" ] || [ ! -d "$COOG_CODE_DIR" ] || [ -z "$COOG_DATA_DIR" ]
then
    {
        echo "Please make sure that these two env vars are set:"
        echo "  COOG_CODE_DIR: your coog-admin install folder"
        echo "  COOG_DATA_DIR: the folder where to keep your custom config"
    } >&2 && exit 1
fi

_commit() {
    config_data_path_changed config \
        && git add config \
        && config_data_commit -m "update config"
}

main() {
    source "$COOG_CODE_DIR/config"
    "$EDITOR" "$COOG_DATA_DIR/config"
    ( cd "$COOG_DATA_DIR" && _commit )
}

main
