#!/bin/bash

if [ -z "$COOG_CODE_DIR" ] || [ -z "$COOG_DATA_DIR" ]
then
    echo "COOG_CODE_DIR or COOG_DATA_DIR not set" >&2 && exit 1
fi

set_args() {
    local args
    if [ ! -z "$ETL_ORIGIN_DB_HOST" ]
    then
        args="-e COOG_HOSTNAME=$ETL_ORIGIN_DB_HOST"
        if [ ! -z "$ETL_ORIGIN_DB_PORT" ]
        then
            args="$args -e COOG_PORT=$ETL_ORIGIN_DB_PORT"
        else
            args="$args -e COOG_PORT=5432"
        fi
    else
        args="$args -e COOG_HOSTNAME=$NETWORK_NAME-postgres -e COOG_PORT=5432"
    fi
    if [ ! -z "$ETL_TARGET_DB_HOST" ]
    then
        args="$args -e DW_HOSTNAME=$ETL_TARGET_DB_HOST"
        if [ ! -z "$ETL_TARGET_DB_PORT" ]
        then
            args="$args -e DW_PORT=$ETL_TARGET_DB_PORT"
        else
            args="$args -e DW_PORT=5432"
        fi
    else
        args="$args -e DW_HOSTNAME=$NETWORK_NAME-dwh -e DW_PORT=5432"
    fi
    args="$args -e COOG_USER=$ETL_ORIGIN_DB_USER"
    args="$args -e COOG_PASSWORD=$ETL_ORIGIN_DB_PASSWORD"
    args="$args -e COOG_DB=$ETL_ORIGIN_DB_NAME"
    args="$args -e DW_USER=$ETL_TARGET_DB_USER"
    args="$args -e DW_PASSWORD=$ETL_TARGET_DB_PASSWORD"
    args="$args -e DW_DB=$ETL_TARGET_DB_NAME"
    echo "$args"
}

_build() {
    (cd "$COOG_CODE_DIR/images/etl" && ./build "$@")
}

_run() {
    docker run \
        $DOCKER_INTERACTIVE_OPTS \
        --network "$NETWORK_NAME" \
        --name "$NETWORK_NAME-etl" \
        $(set_args) \
        "$ETL_IMAGE"
}

usage() {
    echo
    echo "  Available commands "
    echo
    echo "  build               -> Build etl image"
    echo "  run                 -> Run etl image"
    echo "  <action>            -> Call docker action on etl container"
    echo
}

main() {
    source "$COOG_CODE_DIR/config"
    [ -z "$1" ] && usage && return 0
    local cmd; cmd="$1"; shift
    [ "$cmd" = "build" ] && { _build "$@"; return $?; }
    [ "$cmd" = "run" ] && { _run "$@"; return $?; }
    docker "$cmd" "$@" "$NETWORK_NAME-etl"
}

main "$@"
