#!/bin/bash

if [ -z "$COOG_CODE_DIR" ] || [ -z "$COOG_DATA_DIR" ]
then
    echo "COOG_CODE_DIR or COOG_DATA_DIR not set" >&2 && exit 1
fi

migrate() {
    [ -z "$1" ] || config_data_migrate "$1"
}

main() {
    source "$COOG_CODE_DIR/config.fn"
    local v
    if [ -d "$COOG_DATA_DIR" ]
    then
        [ -d "$COOG_DATA_DIR/.git" ] \
            && echo already initialized >&2 \
            && return 1
        [ -z "$1" ] \
            && echo "missing coog version from which you are coming" >&2 \
            && return 1
        v="$1"
    else
        [ ! -z "$1" ] && echo "skipping parameter: $1" >&2
        mkdir "$COOG_DATA_DIR"
    fi

    ( cd "$COOG_DATA_DIR" \
        && config_data_bootstrap \
        && migrate "$v" )
}

main "$@"
