#!/bin/sh
# this script is used to run celery workers for migration

WORKERS=4

if [ ! -z "$1" ]; then
    WORKERS="$1"
fi

./coog celery "$WORKERS" roederer.file.import,\
migrator.party,\
migrator.company,\
migrator.group,\
migrator.address,\
migrator.bank,\
migrator.contact,\
migrator.contract,\
migrator.adhesions,\
account.payment.create,\
account.payment.process,\
account.payment.acknowledge,\
account.payment.do_sepa_messages,\
account.payment.fail,\
account.move.snapshot.take,\
roederer.extract.account_move,\
report_production.request.batch_treat
