#!/bin/bash
# vim: set ft=sh:
# this script creates a docker network for coog

get_dir() {
    local script_path; script_path=$(readlink -f "$0")
    local script_dir; script_dir=$(dirname "$script_path")
    echo "$script_dir"
}

_create() {
    docker network create "$NETWORK_NAME"
}

_rm() {
    docker network rm "$NETWORK_NAME"
}

usage() {
    echo
    echo Available commands
    echo
    echo "  create    -> creates coog network"
    echo "  rm        -> removes coog network"
    echo
}

main() {
    source "$(get_dir)/config"
    #
    [ -z "$1" ] && usage && return 0
    local cmd; cmd=$1; shift
    #
    [ "$cmd" = "create" ] && { _create "$@"; return $?; }
    [ "$cmd" = "rm" ] && { _rm "$@"; return $?; }
    echo "bad command" && return 1
}

main "$@"
