#!/bin/bash

if [ -z "$COOG_CODE_DIR" ] || [ ! -d "$COOG_CODE_DIR" ] || [ -z "$COOG_DATA_DIR" ]
then
    {
        echo "Please make sure that these two env vars are set:"
        echo "  COOG_CODE_DIR: your coog-admin install folder"
        echo "  COOG_DATA_DIR: the folder where to keep your custom config"
    } >&2 && exit 1
fi

_create() {
    docker network create "$NETWORK_NAME"
}

_rm() {
    docker network rm "$NETWORK_NAME"
}

usage() {
    echo
    echo Available commands
    echo
    echo "  create    -> creates coog network"
    echo "  rm        -> removes coog network"
    echo
}

main() {
    source "$COOG_CODE_DIR/config"
    [ -z "$1" ] && usage && return 0
    local cmd; cmd=$1; shift
    [ "$cmd" = "create" ] && { _create "$@"; return $?; }
    [ "$cmd" = "rm" ] && { _rm "$@"; return $?; }
    echo "bad command" && return 1
}

main "$@"
