#!/bin/bash

if [ -z "$COOG_CODE_DIR" ] || [ -z "$COOG_DATA_DIR" ]
then
    echo "COOG_CODE_DIR or COOG_DATA_DIR not set" >&2 && exit 1
fi

_create() {
    docker network create "$NETWORK_NAME"
}

_rm() {
    docker network rm "$NETWORK_NAME"
}

usage() {
    echo
    echo Available commands
    echo
    echo "  create    -> creates coog network"
    echo "  rm        -> removes coog network"
    echo
}

main() {
    source "$COOG_CODE_DIR/config"
    [ -z "$1" ] && usage && return 0
    local cmd; cmd=$1; shift
    [ "$cmd" = "create" ] && { _create "$@"; return $?; }
    [ "$cmd" = "rm" ] && { _rm "$@"; return $?; }
    echo "bad command" && return 1
}

main "$@"
