#!/bin/bash
# This script helps doing with nginx docker image.
# More informations: https://hub.docker.com/_/nginx/

init() {
        [ -e $NGINX_CONF ] && echo backup old config before && return 1
        cp $script_dir/config/nginx.conf $NGINX_CONF
}

edit() {
        [ -z $EDITOR ] && echo '$EDITOR not set' && return 1
        $EDITOR $NGINX_CONF
}

run() {
        [ ! -e $NGINX_CONF ] && echo no config && return 1
        local conf_file; conf_file="/tmp/ngx_"`date +%s%N`".conf"
        cp $NGINX_CONF $conf_file
        local id; id=1
        local name
        local ip
        while [ $id -le $WORKERS ]
        do
                name=$COOG_CONTAINER-$id
                ip=`ip $name`
                [ $? -ne 0 ] && return 1
                sed -i "s/# server coog-backend-host-$id:port-$id/server $ip:7999/" $conf_file
                id=`echo "$id+1" | bc`
        done
        docker run \
                -d \
                --name $NGINX_CONTAINER \
                -p $NGINX_PUB_PORT:80 \
                $NGINX_IMAGE $*
        docker cp $conf_file $NGINX_CONTAINER:/etc/nginx/nginx.conf
        docker exec $NGINX_CONTAINER nginx -s reload
}

action() {
        docker $1 $NGINX_CONTAINER
}

usage() {
        echo
        echo Available commands
        echo
        echo "  init     -> inits nginx.conf"
        echo "  edit     -> edits nginx.conf"
        echo "  run      -> runs an nginx docker image"
        echo "  top      -> shows nginx container top"
        echo "  stats    -> shows nginx container stats"
        echo "  start    -> starts nginx container"
        echo "  stop     -> stops nginx container"
        echo "  restart  -> restarts nginx container"
        echo "  rm       -> removes nginx container"
        echo
}

main() {
        local script_path; script_path=`readlink -f $0`
        local script_dir; script_dir=`dirname $script_path`
        source $script_dir/.env
        #
        [ -z $1 ] && usage && return 1
        local cmd; cmd=$1; shift
        #
        [ $cmd = "init" ] && { init; return $?; }
        [ $cmd = "edit" ] && { edit; return $?; }
        [ $cmd = "run" ] && { run $*; return $?; }
        [ $cmd = "top" ] && { action "top"; return $?; }
        [ $cmd = "stats" ] && { action "stats"; return $?; }
        [ $cmd = "start" ] && { action "start"; return $?; }
        [ $cmd = "stop" ] && { action "stop"; return $?; }
        [ $cmd = "restart" ] && { action "restart"; return $?; }
        [ $cmd = "rm" ] && { action "rm"; return $?; }
        usage && return 1
}

main $*
