#!/bin/bash

if [ -z "$COOG_CODE_DIR" ] || [ -z "$COOG_DATA_DIR" ]
then
    echo "COOG_CODE_DIR or COOG_DATA_DIR not set" >&2 && exit 1
fi

_args() {
    local args
    args="$args -e COOG_PAYBOX_COOG_URL=http://$NETWORK_NAME-nginx:80 -e COOG_PAYBOX_COOG_DB=$COOG_DB_NAME"
    args="$args -e COOG_PAYBOX_COOG_USER=$PAYBOX_COOG_USER -e COOG_PAYBOX_COOG_PASS=$PAYBOX_COOG_PASS"
    args="$args -p $PAYBOX_PUB_PORT:3000"
    [ ! -z "$DEBUG" ] && args="$args -e DEBUG=$DEBUG"
    echo "$args"

}

_run() {
    docker run \
        $DOCKER_DAEMON_OPTS \
        --network "$NETWORK_NAME" \
        --name "$NETWORK_NAME-paybox" \
        $(_args) "$PAYBOX_IMAGE" "$@"
}

_docker() {
    docker "$@" "$NETWORK_NAME-paybox"
}

usage() {
    echo
    echo Available commands
    echo
    echo "  run       -> runs a paybox docker image"
    echo "  <action>  -> calls docker action on paybox container"
    echo
}

main() {
    source "$COOG_CODE_DIR/config"
    [ -z "$1" ] && usage && return 0
    local cmd; cmd="$1"; shift
    [ "$cmd" = "run" ] && { _run "$@"; return $?; }
    _docker "$cmd" "$@"
}

main "$@"
