#!/bin/bash

if [ -z "$COOG_CODE_DIR" ] || [ ! -d "$COOG_CODE_DIR" ] || [ -z "$COOG_DATA_DIR" ]
then
    {
        echo "Please make sure that these two env vars are set:"
        echo "  COOG_CODE_DIR: your coog-admin install folder"
        echo "  COOG_DATA_DIR: the folder where to keep your custom config"
    } >&2 && exit 1
fi

_export_conf_docker() {
    echo "Export shared env"
    export NETWORK_NAME COOG_DB_NAME

    export COOG_URL COOG_DB_NAME

    if [ ! -z "$CUSTOMER" ]
    then
        echo $CUSTOMER
        export CUSTOMER="-$CUSTOMER"
    fi

    export JWT_INTERNAL_ENCRYPTION

    echo "Export portal envs"
    export PORTAL_VERSION 
    
    echo "Export api envs"
    export API_VERSION API_WEB_TOKEN \
        API_MONGO_DB_NAME
    
    echo "Export gateway envs" 
    export GATEWAY_VERSION GATEWAY_WHITELIST COOG_PORTAL_URL JWT_ENCRYPTION \
        JWT_EXPIRATION GATEWAY_WEB_TOKEN GATEWAY_MONGO_DB_NAME COOG_GATEWAY_URL

    if [ -z "$BASE_PATH" ]
    then
        export BASE_PATH=""
    else
        export BASE_PATH
    fi

    if [ -z "$COOG_API_URL" ]
    then
        export COOG_API_URL="http://${NETWORK_NAME}-web"
    else
        export COOG_API_URL
    fi

    if [ -z "$COOG_API_URL_V2" ]
    then
        export COOG_API_URL_V2="http://${NETWORK_NAME}-api"
    else
        export COOG_API_URL_V2
    fi

    if [ -z "$API_MONGO_DB_NAME" ]
    then
        export API_MONGO_DB_NAME=coog-api-v2
    fi

    if [ -z "$GATEWAY_MONGO_DB_NAME" ]
    then
        export GATEWAY_MONGO_DB_NAME=coog-gateway
    fi

    echo "Export gateway authentication activation"
    export COOG_MODULE GOOGLE_MODULE FACEBOOK_MODULE FORCEDOTCOM_MODULE \
        GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET \
        FACEBOOK_CLIENT_ID FACEBOOK_CLIENT_SECRET \
        FORCEDOTCOM_CLIENT_ID FORCEDOTCOM_CLIENT_SECRET 

    echo "Export mongo envs"
    export MONGO_IMAGE MONGO_USER MONGO_PASSWORD MONGO_PORT 
}

_build_conf_docker() {
    echo "set version of images"

    if [ ! -z "$CUSTOMER" ]
    then
        echo $CUSTOMER
        export CUSTOMER="-$CUSTOMER"
    fi

    export PORTAL_VERSION="$1"
    export API_VERSION="$1"
    export GATEWAY_VERSION="$1"
    export REACT_APP_PROD_API_URL REACT_APP_PORTAL_URL
    export MONGO_IMAGE NETWORK_NAME
}

_build() {
    _build_conf_docker "$@"
    cd "$COOG_CODE_DIR/images/portal" && ./build "$@"
}

_up() {
    _export_conf_docker
    cd images/portal
    docker-compose up -d "$@"
}

_restart() {
    _export_conf_docker
    cd images/portal
    docker-compose restart
}

_down() {
    _export_conf_docker
    cd images/portal
    docker-compose down -v "$@"
}

########
# main #
########

usage() {
    echo
    echo Admin commands
    echo
    echo "  build                -> build portal image: <tag> <repo:branch>+"
    echo "  down                 -> shut down all container"
    echo "  down api gateway ... -> shut down relative container"
    echo "  up                   -> running all container"
    echo "  up api gateway ...   -> running relative container"
    return 0
}

main() {
    source "$COOG_CODE_DIR/config"
    [ -z "$1" ] && usage && return 0
    local cmd; cmd="$1"; shift
    [ "$cmd" = "build" ] && { (_build "$@"); return $?; }
    [ "$cmd" = "down" ] && { (_down "$@"); return $?; }
    [ "$cmd" = "up" ] && { (_up "$@"); return $?; }
    [ "$cmd" = "restart" ] && { (_restart "$@"); return $?; }
    usage
}

main "$@"
