#!/bin/bash
# This script helps doing with postgres docker image.
# More informations: https://hub.docker.com/_/postgres/

source ./config

daemon() {
        docker run \
                -d \
                --name $COOG_POSTGRES \
                -e "POSTGRES_USER=$COOG_DB_USERNAME" \
                -e "POSTGRES_PASSWORD=$COOG_DB_PASSWORD" \
                -e "PGDATA=/var/lib/postgresql/data/pgdata" \
                -v $COOG_DB_VOLUME:/var/lib/postgresql/data \
                $COOG_DB_IMAGE
}

client() {
        docker run \
                -ti --rm \
                --link $COOG_POSTGRES:postgres \
                $COOG_DB_IMAGE \
                sh -c 'exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U '"$COOG_DB_USERNAME"
}

[ -z $1 ] && echo Possible commands: daemon - client && exit 1
[ $1 = daemon ] && { shift; daemon $*; exit $?; }
[ $1 = client ] && { shift; client $*; exit $?; }
echo Unknown command && exit 1
