#!/bin/bash
# vim: set ft=sh:
# This script helps doing with postgres docker image.
# More informations: https://hub.docker.com/_/postgres/

get_dir() {
    local script_path; script_path=$(readlink -f "$0")
    local script_dir; script_dir=$(dirname "$script_path")
    echo "$script_dir"
}

server() {
    docker run \
        $DOCKER_DAEMON_OPTS \
        --network "$NETWORK_NAME" \
        --name "$PG_DOCKER_NAME" \
        -e "POSTGRES_USER=$POSTGRES_USER" \
        -e "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" \
        -e "PGDATA=/var/lib/postgresql/data/pgdata" \
        -v /usr/share/zoneinfo:/usr/share/zoneinfo:ro \
        -v /etc/timezone:/etc/timezone:ro \
        -v "$POSTGRES_VOLUME:/var/lib/postgresql/data" \
        -v "/tmp:/tmp" \
        "$POSTGRES_IMAGE" "$@"
}

client() {
    docker run \
        $DOCKER_INTERACTIVE_OPTS \
        --network "$NETWORK_NAME" \
        -v "/tmp:/tmp" \
        "$POSTGRES_IMAGE" \
        psql -h "$PG_DOCKER_NAME" -U "$POSTGRES_USER" "$@"
}

dump() {
    if [ -z "$COOG_POSTGRES_HOST" ]
    then
        docker run \
            $DOCKER_PIPED_OPTS \
            --network "$NETWORK_NAME" \
            -e PGHOST="$PG_DOCKER_NAME" \
            -e PGUSER="$COOG_DB_USER" \
            -e PGPASSWORD="$COOG_DB_PASSWORD" \
            -e PGDATABASE="$COOG_DB_NAME" \
            "$POSTGRES_IMAGE" \
            pg_dump "$@"
    else
        docker run \
            $DOCKER_PIPED_OPTS \
            -e PGHOST="$COOG_POSTGRES_HOST" \
            -e PGUSER="$COOG_DB_USER" \
            -e PGPASSWORD="$COOG_DB_PASSWORD" \
            -e PGDATABASE="$COOG_DB_NAME" \
            "$POSTGRES_IMAGE" \
            pg_dump "$@"
    fi
}

action() {
    docker "$@" "$PG_DOCKER_NAME"
}

usage() {
    echo
    echo Available commands
    echo
    echo "  server    -> runs a postgres docker image as a server"
    echo "  client    -> runs a postgres docker image as a client"
    echo "  dump      -> creates a dump of coog database"
    echo "  <action>  -> calls docker action on server container"
    echo
}

_set_dw_var(){
    source "$(get_dir)/defaults/pentaho.conf"
    POSTGRES_VOLUME="$DW_VOLUME"
    PG_DOCKER_NAME="$PG_DOCKER_NAME-dw"
    COOG_DB_NAME="$DW_DB_NAME"
    COOG_DB_USER="$DW_DB_USER"
    COOG_DB_PASSWORD="$COOG_DB_PASSWORD"
}

main() {
    source "$(get_dir)/config"
    [ ! -z "$PGUSER" ] && COOG_DB_USER="$PGUSER"
    [ ! -z "$PGPASSWORD" ] && COOG_DB_PASSWORD="$PGPASSWORD"
    [ ! -z "$DB_NAME" ] && COOG_DB_NAME="$DB_NAME"
    #
    [ -z "$1" ] && usage && return 0
    local cmd; cmd=$1; shift
    #
    PG_DOCKER_NAME="$NETWORK_NAME-postgres"
    for img; do true; done

    [ "$img" = "dwh" ] &&  _set_dw_var && set -- "${@:1:$(($#-1))}"
    #
    [ "$cmd" = "server" ] && { server "$@"; return $?; }
    [ "$cmd" = "client" ] && { client "$@"; return $?; }
    [ "$cmd" = "dump" ] && { dump "$@"; return $?; }
    action "$cmd" "$@"
}

main "$@"
