#!/bin/bash
# vim: set ft=sh:
# This script helps doing with postgres docker image.
# More informations: https://hub.docker.com/_/postgres/

get_dir() {
        local script_path; script_path=$(readlink -f "$0")
        local script_dir; script_dir=$(dirname "$script_path")
        echo "$script_dir"
}

server() {
        local args
        while [[ ! -z "$1" ]]
        do
                [ "$1" = "--" ] && shift && break
                args="$args $1"
                shift
        done
        docker run \
                $args \
                $DOCKER_DAEMON_OPTS \
                --network "$NETWORK_NAME" \
                --name "$NETWORK_NAME-postgres" \
                -e "POSTGRES_USER=$POSTGRES_USER" \
                -e "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" \
                -e "PGDATA=/var/lib/postgresql/data/pgdata" \
                -v /usr/share/zoneinfo:/usr/share/zoneinfo:ro \
                -v /etc/timezone:/etc/timezone:ro \
                -v "$POSTGRES_VOLUME:/var/lib/postgresql/data" \
                "$POSTGRES_IMAGE" "$@"
}

client() {
        docker run \
                $DOCKER_INTERACTIVE_OPTS \
                --network "$NETWORK_NAME" \
                -v "/tmp:/tmp" \
                "$POSTGRES_IMAGE" \
                psql -h "$NETWORK_NAME-postgres" -U "$POSTGRES_USER" "$@"
}

dump() {
        docker run \
                $DOCKER_PIPED_OPTS \
                --network "$NETWORK_NAME" \
                -e "PGPASSWORD=$PGPASSWORD" \
                -v "/tmp:/tmp" \
                "$POSTGRES_IMAGE" \
                pg_dump -h "$NETWORK_NAME-postgres" -U "$POSTGRES_USER" "$@"
}

action() {
        docker "$@" "$NETWORK_NAME-postgres"
}

usage() {
        echo
        echo Available commands
        echo
        echo "  server    -> runs a postgres docker image as a server"
        echo "  client    -> runs a postgres docker image as a client"
        echo "  <action>  -> calls docker action on server container"
        echo
}

main() {
        source "$(get_dir)/config"
        #
        [ -z "$1" ] && usage && return 0
        local cmd; cmd=$1; shift
        #
        [ "$cmd" = "server" ] && { server "$@"; return $?; }
        [ "$cmd" = "client" ] && { client "$@"; return $?; }
        action "$cmd" "$@"
}

main "$@"
