#!/bin/bash

if [ -z "$COOG_CODE_DIR" ] || [ -z "$COOG_DATA_DIR" ]
then
    echo "COOG_CODE_DIR or COOG_DATA_DIR not set" >&2 && exit 1
fi

main() {
    source "$COOG_CODE_DIR/config"
    docker pull alpine:3.6
    docker pull node:8-alpine
    docker pull python:2-slim
    [ ! -z "$POSTGRES_IMAGE" ] && docker pull "$POSTGRES_IMAGE"
    [ ! -z "$REDIS_IMAGE" ] && docker pull "$REDIS_IMAGE"
    [ ! -z "$NGINX_IMAGE" ] && docker pull "$NGINX_IMAGE"
}

main
