#!/bin/bash
# This script pulls all needed images to run Coog on Docker

main() {
        script_path=`readlink -f $0`
        script_dir=`dirname $script_path`
        source $script_dir/.env
        docker pull martin/docker-cleanup-volumes
        docker pull $PG_IMAGE
        docker pull $REDIS_IMAGE
        docker pull $SENTRY_IMAGE
        docker pull $NGINX_IMAGE
}

main
