#!/bin/bash
# This script helps doing with sentry docker image.
# More informations: https://hub.docker.com/_/sentry/

get_dir() {
        local script_path; script_path=`readlink -f $0`
        local script_dir; script_dir=`dirname $script_path`
        echo $script_dir
}

get_key() {
        [ ! -f $SENTRY_KEY ] && return 1
        cat $SENTRY_KEY
}

set_key() {
        docker run --rm $SENTRY_IMAGE generate-secret-key > $SENTRY_KEY
}

init_conf() {
        [ -e $SENTRY_CONF ] && echo backup old config before && return 1
        install -D `get_dir`/defaults/sentry.yml $SENTRY_CONF
}

edit_conf() {
        [ -z $EDITOR ] && echo '$EDITOR not set' && return 1
        $EDITOR $SENTRY_CONF
}

_run() {
        local secret_key
        secret_key=`get_key`
        [ $? -ne 0 ] && echo "set key before starting" && return 1
        local mode; mode=$1; shift
        local args
        if [ $mode = i ]
        then
                args="-ti --rm"
        elif [ $mode = d ]
        then
                args="-d --name=$SENTRY_CONTAINER-$3"
        elif [ $mode = m ]
        then
                args="-d --name=$SENTRY_CONTAINER"
                [ ! -z $SENTRY_PUB_PORT ] && args="$args -p $SENTRY_PUB_PORT:9000"
        else
                echo "unexpected mode" && return 1
        fi
        docker run \
                $args \
                -e "SENTRY_SECRET_KEY=$secret_key" \
                -e "SENTRY_POSTGRES_HOST=$SENTRY_DB_HOST" \
                -e "SENTRY_POSTGRES_PORT=$SENTRY_DB_PORT" \
                -e "SENTRY_DB_USER=$SENTRY_DB_USERNAME" \
                -e "SENTRY_DB_PASSWORD=$SENTRY_DB_PASSWORD" \
                -e "SENTRY_DB_NAME=$SENTRY_DB_NAME" \
                -e "SENTRY_REDIS_HOST=$REDIS_HOST" \
                -e "SENTRY_REDIS_PORT=$REDIS_PORT" \
                -e "SENTRY_REDIS_DB=$SENTRY_CACHE_DB" \
                -v $SENTRY_VOLUME:/var/lib/sentry/files \
                -v $SENTRY_CONF:/etc/sentry/config.yml \
                $SENTRY_IMAGE $*
}

upgrade() {
        _run i sentry upgrade $*
}

worker() {
        _run d sentry celery worker $*
}

beat() {
        _run d sentry celery beat $*
}

server() {
        _run m $*
}

client() {
        xdg-open "http://$SENTRY_HOST:$SENTRY_PORT"
}

action() {
        docker $1 $SENTRY_CONTAINER $SENTRY_CONTAINER-worker $SENTRY_CONTAINER-beat
}

usage() {
        echo
        echo Available commands
        echo
        echo "  get-key   -> gets secret key (to link workers)"
        echo "  set-key   -> generates secret key"
        echo "  init-conf -> inits sentry configuration file"
        echo "  edit-conf -> edits sentry configuration file"
        echo "  upgrade   -> upgrades sentry database"
        echo "  worker    -> launches a sentry celery worker (docker container)"
        echo "  beat      -> launches a sentry celery beat (docker container)"
        echo "  server    -> launches the sentry server (docker container)"
        echo "  client    -> opens browser on the sentry url"
        echo "  stats     -> shows sentry containers stats"
        echo "  start     -> starts sentry containers"
        echo "  stop      -> stops sentry containers"
        echo "  restart   -> restarts sentry containers"
        echo "  rm        -> removes sentry containers"
        echo
}

main() {
        source `get_dir`/config
        SENTRY_CONF=$SENTRY_VOLUME/config.yml
        #
        [ -z $1 ] && usage && return 1
        local cmd; cmd=$1; shift
        #
        [ $cmd = "get-key" ] && { get_key; return $?; }
        [ $cmd = "set-key" ] && { set_key; return $?; }
        [ $cmd = "init-conf" ] && { init_conf; return $?; }
        [ $cmd = "edit-conf" ] && { edit_conf; return $?; }
        [ $cmd = "upgrade" ] && { upgrade $*; return $?; }
        [ $cmd = "worker" ] && { worker $*; return $?; }
        [ $cmd = "beat" ] && { beat $*; return $?; }
        [ $cmd = "server" ] && { server $*; return $?; }
        [ $cmd = "client" ] && { client $*; return $?; }
        [ $cmd = "stats" ] && { action "stats"; return $?; }
        [ $cmd = "start" ] && { action "start"; return $?; }
        [ $cmd = "stop" ] && { action "stop"; return $?; }
        [ $cmd = "restart" ] && { action "restart"; return $?; }
        [ $cmd = "rm" ] && { action "rm"; return $?; }
        usage && return 1
}

main $*
