#!/bin/bash

if [ -z "$COOG_CODE_DIR" ] || [ ! -d "$COOG_CODE_DIR" ] || [ -z "$COOG_DATA_DIR" ]
then
    {
        echo "Please make sure that these two env vars are set:"
        echo "  COOG_CODE_DIR: your coog-admin install folder"
        echo "  COOG_DATA_DIR: the folder where to keep your custom config"
    } >&2 && exit 1
fi

_build() {
    ( cd "$COOG_CODE_DIR/images/sync" && ./build "$@" )
}

_run() {
    docker run \
        $DOCKER_DAEMON_OPTS \
        --network "$NETWORK_NAME" \
        --name "$NETWORK_NAME-sync" \
        -v "$SYNC_SRC:/src" \
        -v "$SYNC_DEST:/dest" \
        "$SYNC_IMAGE" /src/ /dest/
}

_docker() {
    docker "$@" "$NETWORK_NAME-sync"
}

usage() {
    echo
    echo Available commands
    echo
    echo "  build     -> builds sync image"
    echo "  run       -> runs a sync docker image"
    echo "  <action>  -> calls docker action on sync container"
    echo
}

main() {
    source "$COOG_CODE_DIR/config"
    [ -z "$1" ] && usage && return 0
    local cmd; cmd="$1"; shift
    [ "$cmd" = "build" ] && { _build "$@"; return $?; }
    [ "$cmd" = "run" ] && { _run; return $?; }
    _docker "$cmd" "$@"
}

main "$@"
