#!/bin/bash
# vim: set ft=sh:
# This script helps doing with coog sync image

get_dir() {
        local script_path; script_path=$(readlink -f "$0")
        local script_dir; script_dir=$(dirname "$script_path")
        echo "$script_dir"
}

_build() {
    (cd $(get_dir)/images/sync && docker build -t coog/sync:latest .)
}

_run() {
        docker run \
                $DOCKER_DAEMON_OPTS \
                --network "$NETWORK_NAME" \
                --name "$NETWORK_NAME-sync" \
                -v "$SYNC_SRC:/src" \
                -v "$SYNC_DEST:/dest"
                "$SYNC_IMAGE" -s /src -d /dest
}

_docker() {
        docker "$@" "$NETWORK_NAME-app"
}

usage() {
        echo
        echo Available commands
        echo
        echo "  build     -> builds a sync docker image"
        echo "  run       -> runs a sync docker image"
        echo "  <action>  -> calls docker action on sync container"
        echo
}

main() {
        source "$(get_dir)/config"
        #
        [ -z "$1" ] && usage && return 0
        local cmd; cmd="$1"; shift
        #
        [ "$cmd" = "build" ] && { _build; return $?; }
        [ "$cmd" = "run" ] && { _run; return $?; }
        _docker "$cmd" "$@"
}

main "$@"
