#!/bin/bash
# vim: set ft=sh:

[ -z "$1" ] && echo missing image file && exit 1
[ ! -e "$1" ] && echo bad image file && exit 1

get_dir() {
        local script_path; script_path=$(readlink -f "$0")
        local script_dir; script_dir=$(dirname "$script_path")
        echo "$script_dir"
}

clear_cache() {
        [ ! -z "$COOG_CACHE_DB" ] && "$(get_dir)/redis" client -n "$COOG_CACHE_DB" FLASHDB
}

main() {
        local dir
        dir=$(get_dir)
        source "$dir/config"
        docker load -i "$1"
        echo COOG_IMAGE="$(docker images --format '{{.Repository}}:{{.Tag}}' | head -1)" >> "$PREFIX/config"
        "$dir/nginx" stop
        "$dir/coog" stop
        "$dir/coog" rm
        clear_cache
        "$dir/coog" upgrade
        clear_cache
        "$dir/coog" wsgi
        "$dir/nginx" start
}

main "$@"
