#!/bin/bash

if [ -z "$COOG_CODE_DIR" ] || [ ! -d "$COOG_CODE_DIR" ] || [ -z "$COOG_DATA_DIR" ]
then
    {
        echo "Please make sure that these two env vars are set:"
        echo "  COOG_CODE_DIR: your coog-admin install folder"
        echo "  COOG_DATA_DIR: the folder where to keep your custom config"
    } >&2 && exit 1
fi

_build() {
    ( cd "$COOG_CODE_DIR/images/web" && ./build "$@" )
}

_args() {
    local args
    args="$args -e COOG_API_REDIS_URL=//$NETWORK_NAME-redis:6379 -e COOG_API_REDIS_DB=$WEB_REDIS_DB"
    args="$args -e COOG_API_COOG_URL=http://$NETWORK_NAME-nginx:80 -e COOG_API_COOG_DB=$COOG_DB_NAME"
    [ ! -z "$DEBUG" ] && args="$args -e DEBUG=$DEBUG"
    echo "$args"
}

_docker() {
    docker "$@" "$NETWORK_NAME-web"
}

_image() {
    echo Enter image
    [ -z "$1" ] && echo missing command && return 1
    local cmd; cmd="$1"; shift
    echo Command "$cmd"
    local args
    if [ "$cmd" = server ]
    then
        cmd=web
        args=$DOCKER_DAEMON_OPTS
    else
        args=$DOCKER_INTERACTIVE_OPTS
    fi
    echo args before "$args"
    while [[ ! -z "$1" ]]
    do
        [ "$1" = "--" ] && shift && break
        args="$args $1"
        shift
    done
    echo args after "$args"
    docker run \
        --name "$NETWORK_NAME-$cmd" \
        --network "$NETWORK_NAME" \
        $args \
        $(_args) "$WEB_IMAGE" server "$@"
}

########
# main #
########

usage() {
    echo
    echo Admin commands
    echo
    echo "  build     -> build web image: <tag> <repo:branch>+"
    echo
    echo Docker commands
    echo
    echo "  <action>  -> calls docker action on web container"
    docker run $DOCKER_PIPED_OPTS "$WEB_IMAGE"
    return 0
}

main() {
    source "$COOG_CODE_DIR/config"
    [ -z "$1" ] && usage && return 0
    local cmd; cmd="$1"; shift
    [ "$cmd" = "build" ] && { _build "$@"; return $?; }
    [ "$cmd" = "server" ] && { _image "$cmd" "$@"; return $?; }
    [ "$cmd" = "version" ] && { _image "$cmd" "$@"; return $?; }
    [ "$cmd" = "env" ] && { _image "$cmd" "$@"; return $?; }
    _docker "$cmd" "$@"
}

main "$@"
