#!/bin/bash
FILE="$KETTLE_HOME/.kettle/kettle.properties"
KITCHEN=$PDI_HOME/data-integration/kitchen.sh


main() {
    echo "DW_HOSTNAME=$DW_HOSTNAME">> "$FILE" 
    echo "DW_DB=$DW_DB">>"$FILE"
    echo "DW_PORT=$DW_PORT">>"$FILE"
    echo "DW_USER=$DW_USER">>"$FILE"
    echo "DW_PASSWORD=$DW_PASSWORD">>"$FILE"
    echo "COOG_HOSTNAME=$COOG_HOSTNAME">> "$FILE"
    echo "COOG_DB=$COOG_DB">>"$FILE"
    echo "COOG_PORT=$COOG_PORT">>"$FILE"
    echo "COOG_USER=$COOG_USER">>"$FILE"
    echo "COOG_PASSWORD=$COOG_PASSWORD">>"$FILE"
    cat $FILE
    $KITCHEN -file="$KETTLE_HOME/ETL/Main.kjb"
}

main "$@"


