#!/bin/sh

repo_remote() { # <wd> <repo>
    cat "$1/repos.vendor" "$1/repos.custom" | grep -P "^$2;" | tail -1 | cut -d ";" -f 2
}

repo_fetch() { # <clones> <repo> <remote>
    if [ -d "$1/$2" ]
    then
        echo "  fetch"
        (cd "$1/$2" && git fetch -p -q --recurse-submodules) || return 1
    else
        echo "  clone"
        git clone -q --recurse-submodules "$3" "$1/$2" || return 1
    fi
}

repo_checkout() { # <web> <repo> <branch>
    echo "  checkout"
    git checkout -q "$3" \
        && git merge -q \
        && git submodule update -q --init \
        && echo "$2:$3:$(git rev-parse HEAD)" >> "$1/.version" \
        || return 1
}

repo_cp() { # <web> <repo> <branch>
    local d; d=$(git diff --stat HEAD | wc -l)
    [ "$d" -ne 0 ] && echo "repo $2 not clean" >&2 && return 1

    mkdir "$1/$2" || return 1

    if [ -d build ]
    then
        echo "  build and copy"
        ./build/build "$3" > /dev/null \
            && cp -R ./dist/* "$1/$2/" \
            || return 1
    else
        echo "  copy"
        cp -R ./* "$1/$2/" || return 1
    fi
}

main() { # <image-tag> <repositories> -- [docker-build-arg*]
    [ $# -lt 2 ] && echo missing args >&2 && return 1

    local script_path; script_path=$(readlink -f "$0")
    local wd; wd=$(dirname "$script_path")
    local web; web="$wd/web"
    local clones; clones="$wd/clones"

    touch "$wd/repos.custom"
    mkdir -p "$clones" || return 1
    mkdir "$web" || return 1

    local image; image="$1"
    shift

    while [ ! -z "$1" ]
    do
        [ "$1" = "--" ] && shift && break
        local repo; repo=$(echo "$1" | cut -d ":" -f 1)
        local branch; branch=$(echo "$1" | cut -d ":" -f 2)
        local remote; remote=$(repo_remote "$wd" "$repo")
        echo "workon $repo"
        [ -z "$remote" ] \
            && echo "repo $repo unknown" >&2 \
            && return 1
        repo_fetch "$clones" "$repo" "$remote" || return 1
        (cd "$clones/$repo" && repo_checkout "$web" "$repo" "$branch") || return 1
        (cd "$clones/$repo" && repo_cp "$web" "$repo" "$branch") || return 1
        shift
    done

    find "$web" -name ".git" | xargs rm -rf
    docker build -t "$image" "$@" "$wd"

    rm -rf "$web"
}

main "$@"
