#!/bin/sh
# docker entrypoint

WEB_ROOT=/web

_link() {
    local folder;
    cd $WEB_ROOT
    for f in $(find -maxdepth 2 -name web_modules)
    do
      f=$(dirname $f)
      f=$(basename $f)
      folder="$WEB_ROOT/$f/web_modules"
      [ -d "$folder/app" ] \
          && ln -s "$folder/web_modules/app" "$WEB_ROOT/coog-app/src/custom/$f"\
          && ln -nsf "$WEB_ROOT/coog-app/node_modules" "$folder/app"
      [ -d "$folder/api" ] \
          && ln -s "$folder/api" "$WEB_ROOT/coog-api/api/custom/$f"\
          && ln -nsf "$WEB_ROOT/coog-api/node_modules" "$folder/api"
    done
    return 0
}

_print_version() {
    cat "$WEB_ROOT/.version"
}

_print_env() {
    printenv
}

_server() {
    node svc
}

########
# main #
########

usage() {
    echo
    echo Image commands
    echo
    echo "  version       -> gets image version (git trees)"
    echo "  env           -> gets container env vars"
    echo "  link          -> link customers container"
    echo "  server        -> starts coog server"
    echo
}

main() {
    [ -z "$1" ] && usage && return 1
    local cmd; cmd="$1"; shift
    #
    [ "$cmd" = version ] && { _print_version; return $?; }
    [ "$cmd" = env ] && { _print_env; return $?; }
    [ "$cmd" = link ] && { _link; return $?; }
    [ "$cmd" = server ] && { _server "$@"; return $?; }
    echo "Not supported command" && return 1
}

main "$@"
